name: Building appendheader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: gcc -o appendheader appendheader.c
    - uses: actions/upload-artifact@v4
      with:
            name: build out
            path: ./appendheader
