name: Building appendheader


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
          version: latest
          platform: x64
    - uses: actions/checkout@v4
    - name: build the tool
      run: make build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Binary Release"
          files: out/appendheader
